+++
draft = false
title = "python3-filelock 3.18.0-1"
version = "3.18.0-1"
description = "A platform independent file lock"
date = "2025-03-26T13:59:08"
aliases = "/packages/221111"
categories = ['devel-extra']
upstreamurl = "http://pypi.python.org/pypi/filelock"
arch = "x86_64"
size = "24436"
usize = "139611"
sha1sum = "98cb0093a52105e8a80ee04071431691dd9f2fbf"
depends = "['python3>=3.13']"
reverse_depends = "['python3-cachecontrol', 'python3-cx-freeze', 'python3-poetry', 'python3-virtualenv']"
+++
### Description: 
A platform independent file lock

### Files: 
* /usr/lib/python3.13/site-packages/filelock-3.18.0.dist-info/licenses/LICENSE
* /usr/lib/python3.13/site-packages/filelock-3.18.0.dist-info/METADATA
* /usr/lib/python3.13/site-packages/filelock-3.18.0.dist-info/RECORD
* /usr/lib/python3.13/site-packages/filelock-3.18.0.dist-info/WHEEL
* /usr/lib/python3.13/site-packages/filelock/asyncio.py
* /usr/lib/python3.13/site-packages/filelock/py.typed
* /usr/lib/python3.13/site-packages/filelock/version.py
* /usr/lib/python3.13/site-packages/filelock/_api.py
* /usr/lib/python3.13/site-packages/filelock/_error.py
* /usr/lib/python3.13/site-packages/filelock/_soft.py
* /usr/lib/python3.13/site-packages/filelock/_unix.py
* /usr/lib/python3.13/site-packages/filelock/_util.py
* /usr/lib/python3.13/site-packages/filelock/_windows.py
* /usr/lib/python3.13/site-packages/filelock/__init__.py
* /usr/lib/python3.13/site-packages/filelock/__pycache__/asyncio.cpython-313.opt-1.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/asyncio.cpython-313.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/version.cpython-313.opt-1.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/version.cpython-313.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_api.cpython-313.opt-1.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_api.cpython-313.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_error.cpython-313.opt-1.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_error.cpython-313.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_soft.cpython-313.opt-1.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_soft.cpython-313.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_unix.cpython-313.opt-1.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_unix.cpython-313.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_util.cpython-313.opt-1.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_util.cpython-313.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_windows.cpython-313.opt-1.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/_windows.cpython-313.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/__init__.cpython-313.opt-1.pyc
* /usr/lib/python3.13/site-packages/filelock/__pycache__/__init__.cpython-313.pyc
* /usr/share/doc/python3-filelock-3.18.0/LICENSE
* /usr/share/doc/python3-filelock-3.18.0/README.md
