+++
title = "kernel 3.6.x ext4 data corruption bug"
date = "Fri, 30 Nov 2012 05:50:38 -0600"
author = "ryuo"
categories = ["bug"]
thumbnail.src = "images/categories/bug.png"
thumbnail.visibility = "list"
+++
It appears that this problem has now been patched in the kernel in current.
 Thank you for your patience.