+++
title = "python"
date = "2006-10-12"
+++
* Author: voroskoi
* Vulnerable: 2.4.3-3
* Unaffected: 2.4.3-4siwenna1


A vulnerability has been reported in Python, which can be exploited by malicious people to cause a DoS (Denial of Service) and potentially compromise a vulnerable system.
* Bug Tracker URL: http://bugs.frugalware.org/task/1284
## CVEs:
* http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2006-4980
